line_length:
  warning: 300
type_body_length:
  warning: 500
file_length:
  warning: 750
function_body_length:
  warning: 50
  error: 80
cyclomatic_complexity:
  warning: 10
  error: 15

disabled_rules:
  - trailing_whitespace

excluded:
  - .git
  - Pods
  - Carthage
